database:
  URL: 'mongodb+srv://sadat:sadat642@dokanio.zqlyd.mongodb.net/swiftex?authSource=admin&replicaSet=atlas-14h9s4-shard-0&readPreference=primary'
  name: 'swiftex'

server:
  host: 'localhost'
  name: 'swiftex'
  port: 4521
  bcrypt_cost: 12

jwt:
  secret: '@sec43tv3r788#4a'
  TTL: 168
